name: flutter_support_pack
description: Commanly used features in on package to reduce number of imports and dependancy issues
version: 1.2.3
homepage: https://github.com/pasaneramusugoda/flutter_support_pack

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.4.0
  firebase_crashlytics: ^3.0.7
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: