name: flutter_support_pack
description: Commanly used features in on package to reduce number of imports and dependancy issues
version: 1.0.0
homepage: https://github.com/pasaneramusugoda/flutter_support_pack

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.17.0
  firebase_crashlytics: ^2.8.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: