name: flutter_support_pack
description: Commanly used features in on package to reduce number of imports and dependancy issues
version: 0.0.4
homepage: https://github.com/pasaneramusugoda/flutter_support_pack

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.5.2+1
  firebase_crashlytics: ^0.2.3+1
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: