name: flutter_support_pack
description: Commonly used features in on package to reduce number of imports and dependency issues
version: 1.2.5
homepage: https://github.com/pasaneramusugoda/flutter_support_pack

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: '>=2.4.1'
  firebase_crashlytics: '>=3.0.11'
  intl: '>=0.17.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

scripts:
  gen_change_log: git-chglog -o CHANGELOG.md