name: flutter_support_pack
description: Commanly used features in on package to reduce number of imports and dependancy issues
version: 0.0.6+5
homepage: https://github.com/pasaneramusugoda/flutter_support_pack

environment:
  sdk: ">=2.10.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.4
  firebase_crashlytics: ^2.0.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: